[package]
name = "cyancia_render"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
cyancia_utils.workspace = true
wesl.workspace = true
encase.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true

[build-dependencies]
wesl.workspace = true
