[package]
name = "example_input"
version = "0.1.0"
edition = "2024"

[dependencies]
cyancia_input.workspace = true
cyancia_assets.workspace = true
tracing-subscriber.workspace = true
iced_core.workspace = true
cyancia_id.workspace = true
