[package]
name = "cyancia_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot.workspace = true
iced_core.workspace = true
cyancia_id.workspace = true
cyancia_input.workspace = true
cyancia_canvas.workspace = true
glam.workspace = true
cyancia_math.workspace = true
