[package]
name = "cyancia_id"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid.workspace = true
xxhash-rust.workspace = true
serde.workspace = true
cyancia_utils.workspace = true
parking_lot.workspace = true
